### ISSUE TITLE
Error: Cannot find module '/user_code/next/server/pages-manifest.json'

### ISSUE THREAD

**Issue by thomasdavis** [jthegedus/firebase-functions-next-example#21]
Currently getting this error in Firebase logs on my repo forked from here.

I couldn't solve it so cloned this repo fresh and did,

```
yarn install
yarn deploy-all
```

Which resulted in the same error. Any one else?

**Comment by bennygenel** [comment]
@thomasdavis Did you solve the problem?

I am getting the same error you got. 

Steps to reproduce

- Clone the repo
- Change `projectId` with mine
- run `yarn install`
- run `yarn deploy-app` or `yarn deploy-all`

Results with the below errors;

```
Error: Cannot find module '/user_code/next/server/pages-manifest.json'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at getPagePath (/user_code/node_modules/next/dist/server/require.js:52:23)
    at _callee$ (/user_code/node_modules/next/dist/server/require.js:82:24)
    at tryCatch (/user_code/node_modules/next/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/user_code/node_modules/next/node_modules/regenerator-runtime/runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/user_code/node_modules/next/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/user_code/node_modules/next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
```

```
{ Error: Cannot find module '/user_code/next/server/bundles/pages/_document'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at _callee3$ (/user_code/node_modules/next/dist/server/render.js:206:17)
    at tryCatch (/user_code/node_modules/next/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/user_code/node_modules/next/node_modules/regenerator-runtime/runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/user_code/node_modules/next/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/user_code/node_modules/next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/user_code/node_modules/next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9) code: 'MODULE_NOT_FOUND', sourceMapsApplied: true }
```

**Comment by ckj** [comment]
Same. @bennygenel did you find a solution?

**Comment by harrisonlo** [comment]
Same here. @jthegedus could you help us out?

**Comment by harrisonlo** [comment]
Here's my entire error log from the firebase console:

![image](https://user-images.githubusercontent.com/7886751/43874903-e12ca7d6-9bc0-11e8-90f1-d2fe8bf1fd2d.png)

**Comment by harrisonlo** [comment]
Okay, so I figured out what the issue is. `"next": "^6.0.3"` (which this repo has) generates `dist/functions/next/dist/` in build but Firebase was looking for `dist/functions/next/server`. 

Updating next to the latest version `"next": "^6.1.1"` seems to solve the problem.

**Comment by jthegedus** [comment]
Hi all, sorry for not getting back to you sooner. I am deprecating this example in favor of another approach, which can be found in this repo (https://github.com/jthegedus/firebase-gcp-examples/tree/master/functions-nextjs).

I've been very busy the last few months and getting back into the swing of OSS and writing so if you are having issues I will truly try and be more prompt next time. Thanks @harrisonlo for jumping in and sharing your thoughts here, I really appreciate the help. Cheers.
