### ISSUE TITLE
Anyone had any luck with firebase functions on node 8 and next 6.1

### ISSUE THREAD

**Issue by piuccio** [jthegedus/firebase-functions-next-example#22]
I tried deploying to firebase functions using `{engines: { node: 8 } }` and after several struggles I'm stuck at

```
{ Error: Cannot find module 'next/document'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.21 (/srv/next/server/bundles/pages/_document.js:223:18)
    at __webpack_require__ (/srv/next/server/bundles/pages/_document.js:23:31)
    at Object.20 (/srv/next/server/bundles/pages/_document.js:107:72)
    at __webpack_require__ (/srv/next/server/bundles/pages/_document.js:23:31)
    at Object.19 (/srv/next/server/bundles/pages/_document.js:92:18)
    at __webpack_require__ (/srv/next/server/bundles/pages/_document.js:23:31) code: 'MODULE_NOT_FOUND' }
```

I also have `Error: Cannot find module 'next/error'` but I figure that's the same thing

**Comment by paintedbicycle** [comment]
I'm also very interested in this, especially since I think it removes the Babel step for most setups.

**Comment by paintedbicycle** [comment]
I had no trouble with the following:
- I updated babel

```
  "dependencies": {
    "firebase-admin": "^6.0.0",
    "firebase-functions": "^2.0.5",
    "@babel/runtime": "^7.1.2",
    "next": "^7.0.1",
    ...
  },

  "devDependencies": {
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/preset-env": "^7.1.0"
    ...
  }
```

and

in `.babelrc`
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "8.11.1"
        }
      }
    ]
  ]
}
```


- I'm using the latest firebase tools
- I used node: engine 8 as you mentioned above

I am not using _document.js but I am using _app.js

Paul

**Comment by jthegedus** [comment]
Hi all, sorry for not getting back to you sooner. I am deprecating this example in favor of another approach, which can be found in this repo (https://github.com/jthegedus/firebase-gcp-examples/tree/master/functions-nextjs).

I've been very busy the last few months and getting back into the swing of OSS and writing so if you are having issues I will truly try and be more prompt next time. Thanks @paintedbicycle for jumping in and sharing your thoughts here, I really appreciate the help. Cheers.
