### ISSUE TITLE
Unexpected identifier prepare() on function deploy

### ISSUE THREAD

**Issue by ohsnaplol** [jthegedus/firebase-functions-next-example#29]
After trying to add my own functions and deploying them I get the following error: 

```
Detailed stack trace: /user_code/node_modules/next/node_modules/next-server/dist/server/next-server.js:93
    async prepare() { }
          ^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/next/node_modules/next-server/index.js:2:52)
```

This along with a typical "Unable to deploy functions error". I've made sure all dependencies are installed and I'm logged in and everything. Here's an excerpt from my yarn error log: 

```
Arguments: 
  /usr/local/bin/node /usr/local/bin/yarn deploy-functions

PATH: 
  /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/git/bin

Yarn version: 
  1.5.1

Node version: 
  10.15.0

Platform: 
  darwin x64

```

This is happening on both my mac and windows (linux subsystem) environments

**Comment by ohsnaplol** [comment]
I believe the problem is that I wasn't building the functions before deploying.
